# Generated by Django 5.0.6 on 2025-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mode', models.CharField(default='local_file', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=128)),
                ('results_path', models.CharField(blank=True, default='', max_length=255)),
                ('download_url', models.CharField(blank=True, default='', max_length=512)),
                ('batches', models.IntegerField(default=0)),
                ('state', models.CharField(default='QUEUED', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
