# Generated by Django 5.0.6 on 2025-09-21 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='id',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='handoff_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='download_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='results_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='state',
            field=models.CharField(default='PENDING', max_length=32),
        ),
        migrations.AlterModelTable(
            name='jobrun',
            table='core_job_run',
        ),
    ]
